.TH NXSTAT 1 "31 Jul 2015" 
.UC 4 
.SH NAME 
nxcmd \- send commands to a NX-8/NX-8V/NX-8E Alarm Panel.


.SH SYNOPSIS 
.B nxcmd
[ 
.B options 
]
<
.B command
>
[
. B command arguments
]


.SH DESCRIPTION 
.I nxcmd
is a utlitiy to display send commands to a alarm panel, that
is being monitored by nxgipd daemon.

This tool can be used to perform most keypad functions (if corresponding
commands are enabled in NX-584 configuration).
Additionally this command supports some special functionality not available
via normal keypads, like sending X-10 messages or displaying custom text
messages on NX-148e (LCD) keypads.




.SH OPTIONS
.PP
Options may be either the traditional POSIX one letter options, or the
GNU style long options.  POSIX style options start with a single
``\-'', while GNU long options start with ``\-\^\-''.

Options offered by
.I nxcmd
are the following:
.TP 0.6i
.B -c <configfile>, --conf=<configfile>
Specifies the pathname of the configuration file. If not used program
will look for
.I /etc/nxgipd.conf
.TP 0.6i
.B -h, --help
Display short usage information and exit.
.TP 0.6i
.B -n, --nowait
Do not wait for response from server for the command.
.TP 0.6i
.B -t <n>, --timeout=<n>
Timeout (in seconds) for how long to wait response from the server.
Default is 10 seconds.
.TP 0.6i
.B -p <n>, --partition=<n>
Partition that the command should be applied to. Default is first partition (1).
.TP 0.6i
.B -v, --verbose
Enable more verbose output to stdout (when not running as daemon).
.TP 0.6i
.B -V, --version
Print program version and exit.


.SH COMMANDS
.PP
.B nxcmd 
sends one command at a time to the alarm panel. Depending on the command
there may be mandatory parameters required.


.B Commands (no PIN required):

.TP 0.6i
exit
Same as pressing "Exit" button on the keypad. If one button arm is enabled this will arm the system in away mode. If system is already armed this will toggle "Instat" mode (if it is enabled by alarm configuration).

.TP 0.6i
stay
Same as pressing "Stay" button on the keypad. If one button arm is enabled this will arm the system in stay mode. If system is already armed this will toggle "Interiors" (if it is enabled by alarm configuration).

.TP 0.6i
chime
Same as pressing "Chime" button on the keypad. This will toggle the chime mode.

.TP 0.6i
bypass
Toggle bypass status of "interior" sonze.

.TP 0.6i
grpbypass
Group bypass.

.TP 0.6i
smokereset
Smoke detector manual reset.

.TP 0.6i
sounder
Enabled (turn on) keypad sounder.

.PP

.TP 0.6i 
zonebypass <zone number>
Togle bypass of given zone. Zone numbers are 1..192 range.

.TP 0.6i
x10 <house> <unit> <function>
Send X-10 Command. House parameter is a letter from A to P.
Unit parameter is number from 1 to 16. 
And function is one of the following: 
.I
on, off, dim, bright, lights-on, lights-off, units-off

.TP 0.6i
message <n> <line1> <line2> <sec>
Display custom message on designated pinpad for short amount of time. Parameter
.I n
specifies the pinpad (1=first pinpad). Parameters
.I text1
and
.I text2
specify two upto 16 character strings to display on the LCD 
keypad screen (this works only on NX-148e keypads).
Final argument
.I sec
specifies how many seconds the message should be displayed (valid range 0-255).

.TP 0.6i
getprogram <device> <location>
Read program data (configuration) values from given device. Output is sent to nxgipd process log file (and/or to syslog depending on the configuration).  Device parameter specifies the device bus address (valid range for device is 0..255), and location parameter specifies with configuration item to read from the given device (valid range for location is 0.4095)
Consult the alarm panel or accessory/device documentation for the device bus addresses and applicaple program location numbers.

NOTE! Alarm panel itself is usually device number 8 (and not device 0 like when programming from a keypad).
Also it is not possible to get the program data of the NX-584 itself (device 72).

.TP 0.6i
.B Commands (PIN required):

.TP 0.6i
armaway
Arm in Away mode. By default this affects partition 1, alternate target partition may be specified using the  
.I --partition, -p
option.

.TP 0.6i
armstay
Arm in Stay mode. By default this affects partition 1, alternate target partition may be specified using the  
.I --partition, -p
option.

.TP 0.6i
disarm
Disarm partition. This will disarm partition 1 unless otherwise specified using the
.I --partition, -p
option.

.TP 0.6i
silence
Turn off any sounder or alarm. This will turn of the main siren as well as keyboard sounder(s).

.TP 0.6i
cancel
Cancel Alarm. This will send alarm cancellation message.

.TP 0.6i
autoarm
Initiate auto-arm process.


.SH SECURITY

Some of the commands offered by nxcmd could potentially make your alarm system slightly less secure, while offering convenience of being able to remotely control the system. NX-584 interface configuration determines which (if any) of these commands will be available.

Relevant commands to enable (in NX-584 configuration) for full functionaliy are the following:


.TP 0.6i
Secondary Keypad Function (3Eh)

.TP 0.6i
Primary Keypad Function with PIN (3Ch)

.TP 0.6i
Send X-10 Message (28h)

.TP 0.6i
Send Keypad Text Message (2Bh) & Keypad Terminal Mode Request (2Ch)

.TP 0.6i
Program Data Request (30h)





.SH "SEE ALSO" 
nxgipd(1) nxstat(1)

.SH AUTHOR
Timo Kokkonen <tjko@iki.fi>

.SH COPYING
Copyright (C) 2009-2015  Timo Kokkonen

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
 This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
 You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
